// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CattolicaSpecflowTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("LinkedIn LogIn Tests", SourceFile="Features\\LogIn.feature", SourceLine=0)]
    public partial class LinkedInLogInTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LogIn.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "LinkedIn LogIn Tests", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Chrome -  I can login as a user with my correct username and password", new string[] {
                "Smoke",
                "Browser:Chrome"}, SourceLine=4)]
        public virtual void Chrome_ICanLoginAsAUserWithMyCorrectUsernameAndPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Chrome -  I can login as a user with my correct username and password", new string[] {
                        "Smoke",
                        "Browser:Chrome"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.Given("I navigate to the https://www.linkedin.com website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.And("I enter kiszols@yahoo.com as the user_name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
testRunner.And("I enter Stridentb52 as the pass_word", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
testRunner.When("I select the sign_in_button element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
testRunner.Then("I should see the user_profile element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Firefox -  I can login as a user with my correct username and password", new string[] {
                "Regression",
                "Browser:Firefox"}, SourceLine=14)]
        public virtual void Firefox_ICanLoginAsAUserWithMyCorrectUsernameAndPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Firefox -  I can login as a user with my correct username and password", new string[] {
                        "Regression",
                        "Browser:Firefox"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("I navigate to the https://www.linkedin.com website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
testRunner.And("I enter kiszols@yahoo.com as the user_name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
testRunner.And("I enter Stridentb52 as the pass_word", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
testRunner.When("I select the sign_in_button element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
testRunner.Then("I should see the user_profile element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("IE -  I can login as a user with my correct username and password", new string[] {
                "Regression",
                "Browser:IE"}, SourceLine=24)]
        public virtual void IE_ICanLoginAsAUserWithMyCorrectUsernameAndPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("IE -  I can login as a user with my correct username and password", new string[] {
                        "Regression",
                        "Browser:IE"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
testRunner.Given("I navigate to the https://www.linkedin.com website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
testRunner.And("I enter kiszols@yahoo.com as the user_name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
testRunner.And("I enter Stridentb52 as the pass_word", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
testRunner.When("I select the sign_in_button element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
testRunner.Then("I should see the user_profile element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void Chrome_ICanNotLoginAsUserWithNotCorrectUsernameAndPassword(string user_Name, string pass_Word, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Smoke",
                    "Browser:Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Chrome -  I can not login as user with not correct username and password", @__tags);
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
testRunner.Given("I navigate to the https://www.linkedin.com website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
testRunner.And(string.Format("I enter {0} as the user_name", user_Name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
testRunner.And(string.Format("I enter {0} as the pass_word", pass_Word), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
testRunner.When("I select the sign_in_button element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
testRunner.Then("I should not see the user_profile element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Chrome -  I can not login as user with not correct username and password, kiszols" +
            "@yahoo.com1", new string[] {
                "Smoke",
                "Browser:Chrome",
                "source:TestData.xlsx:LogIn"}, SourceLine=0)]
        public virtual void Chrome_ICanNotLoginAsUserWithNotCorrectUsernameAndPassword_KiszolsYahoo_Com1()
        {
            this.Chrome_ICanNotLoginAsUserWithNotCorrectUsernameAndPassword("kiszols@yahoo.com1", "Stridentb521", new string[] {
                        "source:TestData.xlsx:LogIn"});
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
