// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CattolicaSpecflowTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Linkedin SignIn Tests", SourceFile="Features\\SignIN.feature", SourceLine=0)]
    public partial class LinkedinSignInTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SignIN.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Linkedin SignIn Tests", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword(string user_Name, string pass_Word, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Chrome - I can signin as a user with not correct username and password", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.Given("I navigate to the https://www.linkedin.com/ website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.And("I am on the SignInPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
testRunner.And(string.Format("I enter {0} as the user_name_entry", user_Name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
testRunner.And(string.Format("I enter {0} as the pass_word_entry", pass_Word), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
testRunner.When("I select the sign_in_button element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
testRunner.And("I am on the MainPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
testRunner.Then("I should see the user_profile_image element", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
testRunner.And("I should signout", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Chrome - I can signin as a user with not correct username and password, Variant 0" +
            "", new string[] {
                "Regression",
                "source:TestData.xlsx:SignIn"}, SourceLine=0)]
        public virtual void Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword_Variant0()
        {
            this.Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword("kzol", "Test1234", new string[] {
                        "source:TestData.xlsx:SignIn"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Chrome - I can signin as a user with not correct username and password, Variant 1" +
            "", new string[] {
                "Regression",
                "source:TestData.xlsx:SignIn"}, SourceLine=0)]
        public virtual void Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword_Variant1()
        {
            this.Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword("kzol", "", new string[] {
                        "source:TestData.xlsx:SignIn"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Chrome - I can signin as a user with not correct username and password, Variant 2" +
            "", new string[] {
                "Regression",
                "source:TestData.xlsx:SignIn"}, SourceLine=0)]
        public virtual void Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword_Variant2()
        {
            this.Chrome_ICanSigninAsAUserWithNotCorrectUsernameAndPassword("", "Test1234", new string[] {
                        "source:TestData.xlsx:SignIn"});
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
