//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZolCo.ProductTests.BatchRunService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchRequest", Namespace="http://schemas.datacontract.org/2004/07/CloasBatchProcess")]
    [System.SerializableAttribute()]
    public partial class BatchRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZolCo.ProductTests.BatchRunService.BatchType BatchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[][] ControlCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CycleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DoNotQueueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromRunDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromRunNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeDTFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeInternalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeOutputProcessingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZolCo.ProductTests.BatchRunService.PricingType PricingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToRunDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToRunNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZolCo.ProductTests.BatchRunService.BatchType BatchType {
            get {
                return this.BatchTypeField;
            }
            set {
                if ((this.BatchTypeField.Equals(value) != true)) {
                    this.BatchTypeField = value;
                    this.RaisePropertyChanged("BatchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] ControlCards {
            get {
                return this.ControlCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlCardsField, value) != true)) {
                    this.ControlCardsField = value;
                    this.RaisePropertyChanged("ControlCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cycle {
            get {
                return this.CycleField;
            }
            set {
                if ((this.CycleField.Equals(value) != true)) {
                    this.CycleField = value;
                    this.RaisePropertyChanged("Cycle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Database {
            get {
                return this.DatabaseField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseField, value) != true)) {
                    this.DatabaseField = value;
                    this.RaisePropertyChanged("Database");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DoNotQueue {
            get {
                return this.DoNotQueueField;
            }
            set {
                if ((this.DoNotQueueField.Equals(value) != true)) {
                    this.DoNotQueueField = value;
                    this.RaisePropertyChanged("DoNotQueue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromRunDate {
            get {
                return this.FromRunDateField;
            }
            set {
                if ((this.FromRunDateField.Equals(value) != true)) {
                    this.FromRunDateField = value;
                    this.RaisePropertyChanged("FromRunDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromRunNumber {
            get {
                return this.FromRunNumberField;
            }
            set {
                if ((this.FromRunNumberField.Equals(value) != true)) {
                    this.FromRunNumberField = value;
                    this.RaisePropertyChanged("FromRunNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeDTF {
            get {
                return this.IncludeDTFField;
            }
            set {
                if ((this.IncludeDTFField.Equals(value) != true)) {
                    this.IncludeDTFField = value;
                    this.RaisePropertyChanged("IncludeDTF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeInternals {
            get {
                return this.IncludeInternalsField;
            }
            set {
                if ((this.IncludeInternalsField.Equals(value) != true)) {
                    this.IncludeInternalsField = value;
                    this.RaisePropertyChanged("IncludeInternals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeOutputProcessing {
            get {
                return this.IncludeOutputProcessingField;
            }
            set {
                if ((this.IncludeOutputProcessingField.Equals(value) != true)) {
                    this.IncludeOutputProcessingField = value;
                    this.RaisePropertyChanged("IncludeOutputProcessing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phase {
            get {
                return this.PhaseField;
            }
            set {
                if ((this.PhaseField.Equals(value) != true)) {
                    this.PhaseField = value;
                    this.RaisePropertyChanged("Phase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZolCo.ProductTests.BatchRunService.PricingType PricingType {
            get {
                return this.PricingTypeField;
            }
            set {
                if ((this.PricingTypeField.Equals(value) != true)) {
                    this.PricingTypeField = value;
                    this.RaisePropertyChanged("PricingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName {
            get {
                return this.RegionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionNameField, value) != true)) {
                    this.RegionNameField = value;
                    this.RaisePropertyChanged("RegionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Run {
            get {
                return this.RunField;
            }
            set {
                if ((this.RunField.Equals(value) != true)) {
                    this.RunField = value;
                    this.RaisePropertyChanged("Run");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToRunDate {
            get {
                return this.ToRunDateField;
            }
            set {
                if ((this.ToRunDateField.Equals(value) != true)) {
                    this.ToRunDateField = value;
                    this.RaisePropertyChanged("ToRunDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToRunNumber {
            get {
                return this.ToRunNumberField;
            }
            set {
                if ((this.ToRunNumberField.Equals(value) != true)) {
                    this.ToRunNumberField = value;
                    this.RaisePropertyChanged("ToRunNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchType", Namespace="http://schemas.datacontract.org/2004/07/CloasBatchProcess.Helpers")]
    public enum BatchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Skip = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FmOnly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Full = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PricingType", Namespace="http://schemas.datacontract.org/2004/07/CloasBatchProcess.Helpers")]
    public enum PricingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Increasing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoIncrease = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchResponse", Namespace="http://schemas.datacontract.org/2004/07/CloasBatchProcess")]
    [System.SerializableAttribute()]
    public partial class BatchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZolCo.ProductTests.BatchRunService.JobResponse[] JobResponsesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZolCo.ProductTests.BatchRunService.JobResponse[] JobResponses {
            get {
                return this.JobResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.JobResponsesField, value) != true)) {
                    this.JobResponsesField = value;
                    this.RaisePropertyChanged("JobResponses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobResponse", Namespace="http://schemas.datacontract.org/2004/07/CloasBatchProcess")]
    [System.SerializableAttribute()]
    public partial class JobResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName {
            get {
                return this.JobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNameField, value) != true)) {
                    this.JobNameField = value;
                    this.RaisePropertyChanged("JobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((this.JobNumberField.Equals(value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCodeField, value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://schemas.datacontract.org/2004/07/CloasBatchProcess.Helpers")]
    public enum JobStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InQueue = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BatchRunService.IBatchService")]
    public interface IBatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/InvokeBatch", ReplyAction="http://tempuri.org/IBatchService/InvokeBatchResponse")]
        ZolCo.ProductTests.BatchRunService.BatchResponse InvokeBatch(ZolCo.ProductTests.BatchRunService.BatchRequest batchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/InvokeBatch", ReplyAction="http://tempuri.org/IBatchService/InvokeBatchResponse")]
        System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.BatchResponse> InvokeBatchAsync(ZolCo.ProductTests.BatchRunService.BatchRequest batchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/GetJobStatus", ReplyAction="http://tempuri.org/IBatchService/GetJobStatusResponse")]
        ZolCo.ProductTests.BatchRunService.GetJobStatusResponse GetJobStatus(ZolCo.ProductTests.BatchRunService.GetJobStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/GetJobStatus", ReplyAction="http://tempuri.org/IBatchService/GetJobStatusResponse")]
        System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.GetJobStatusResponse> GetJobStatusAsync(ZolCo.ProductTests.BatchRunService.GetJobStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/StartRegion", ReplyAction="http://tempuri.org/IBatchService/StartRegionResponse")]
        ZolCo.ProductTests.BatchRunService.StartRegionResponse StartRegion(ZolCo.ProductTests.BatchRunService.StartRegionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/StartRegion", ReplyAction="http://tempuri.org/IBatchService/StartRegionResponse")]
        System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.StartRegionResponse> StartRegionAsync(ZolCo.ProductTests.BatchRunService.StartRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/StopRegion", ReplyAction="http://tempuri.org/IBatchService/StopRegionResponse")]
        ZolCo.ProductTests.BatchRunService.StopRegionResponse StopRegion(ZolCo.ProductTests.BatchRunService.StopRegionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/StopRegion", ReplyAction="http://tempuri.org/IBatchService/StopRegionResponse")]
        System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.StopRegionResponse> StopRegionAsync(ZolCo.ProductTests.BatchRunService.StopRegionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/KillJob", ReplyAction="http://tempuri.org/IBatchService/KillJobResponse")]
        ZolCo.ProductTests.BatchRunService.KillJobResponse KillJob(ZolCo.ProductTests.BatchRunService.KillJobRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatchService/KillJob", ReplyAction="http://tempuri.org/IBatchService/KillJobResponse")]
        System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.KillJobResponse> KillJobAsync(ZolCo.ProductTests.BatchRunService.KillJobRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetJobStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string regionName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int jobNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string userId;
        
        public GetJobStatusRequest() {
        }
        
        public GetJobStatusRequest(string clientName, string regionName, int jobNumber, string userId) {
            this.clientName = clientName;
            this.regionName = regionName;
            this.jobNumber = jobNumber;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetJobStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZolCo.ProductTests.BatchRunService.JobStatus GetJobStatusResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string outputMessage;
        
        public GetJobStatusResponse() {
        }
        
        public GetJobStatusResponse(ZolCo.ProductTests.BatchRunService.JobStatus GetJobStatusResult, string outputMessage) {
            this.GetJobStatusResult = GetJobStatusResult;
            this.outputMessage = outputMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartRegion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string regionName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string userId;
        
        public StartRegionRequest() {
        }
        
        public StartRegionRequest(string clientName, string regionName, string userId) {
            this.clientName = clientName;
            this.regionName = regionName;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartRegionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StartRegionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string outputMessage;
        
        public StartRegionResponse() {
        }
        
        public StartRegionResponse(int StartRegionResult, string outputMessage) {
            this.StartRegionResult = StartRegionResult;
            this.outputMessage = outputMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StopRegion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StopRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string regionName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string userId;
        
        public StopRegionRequest() {
        }
        
        public StopRegionRequest(string clientName, string regionName, string userId) {
            this.clientName = clientName;
            this.regionName = regionName;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StopRegionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StopRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StopRegionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string outputMessage;
        
        public StopRegionResponse() {
        }
        
        public StopRegionResponse(int StopRegionResult, string outputMessage) {
            this.StopRegionResult = StopRegionResult;
            this.outputMessage = outputMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KillJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KillJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clientName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string regionName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int jobNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string userId;
        
        public KillJobRequest() {
        }
        
        public KillJobRequest(string clientName, string regionName, int jobNumber, string userId) {
            this.clientName = clientName;
            this.regionName = regionName;
            this.jobNumber = jobNumber;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KillJobResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KillJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int KillJobResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string outputMessage;
        
        public KillJobResponse() {
        }
        
        public KillJobResponse(int KillJobResult, string outputMessage) {
            this.KillJobResult = KillJobResult;
            this.outputMessage = outputMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBatchServiceChannel : ZolCo.ProductTests.BatchRunService.IBatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatchServiceClient : System.ServiceModel.ClientBase<ZolCo.ProductTests.BatchRunService.IBatchService>, ZolCo.ProductTests.BatchRunService.IBatchService {
        
        public BatchServiceClient() {
        }
        
        public BatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZolCo.ProductTests.BatchRunService.BatchResponse InvokeBatch(ZolCo.ProductTests.BatchRunService.BatchRequest batchRequest) {
            return base.Channel.InvokeBatch(batchRequest);
        }
        
        public System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.BatchResponse> InvokeBatchAsync(ZolCo.ProductTests.BatchRunService.BatchRequest batchRequest) {
            return base.Channel.InvokeBatchAsync(batchRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZolCo.ProductTests.BatchRunService.GetJobStatusResponse ZolCo.ProductTests.BatchRunService.IBatchService.GetJobStatus(ZolCo.ProductTests.BatchRunService.GetJobStatusRequest request) {
            return base.Channel.GetJobStatus(request);
        }
        
        public ZolCo.ProductTests.BatchRunService.JobStatus GetJobStatus(string clientName, string regionName, int jobNumber, string userId, out string outputMessage) {
            ZolCo.ProductTests.BatchRunService.GetJobStatusRequest inValue = new ZolCo.ProductTests.BatchRunService.GetJobStatusRequest();
            inValue.clientName = clientName;
            inValue.regionName = regionName;
            inValue.jobNumber = jobNumber;
            inValue.userId = userId;
            ZolCo.ProductTests.BatchRunService.GetJobStatusResponse retVal = ((ZolCo.ProductTests.BatchRunService.IBatchService)(this)).GetJobStatus(inValue);
            outputMessage = retVal.outputMessage;
            return retVal.GetJobStatusResult;
        }
        
        public System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.GetJobStatusResponse> GetJobStatusAsync(ZolCo.ProductTests.BatchRunService.GetJobStatusRequest request) {
            return base.Channel.GetJobStatusAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZolCo.ProductTests.BatchRunService.StartRegionResponse ZolCo.ProductTests.BatchRunService.IBatchService.StartRegion(ZolCo.ProductTests.BatchRunService.StartRegionRequest request) {
            return base.Channel.StartRegion(request);
        }
        
        public int StartRegion(string clientName, string regionName, string userId, out string outputMessage) {
            ZolCo.ProductTests.BatchRunService.StartRegionRequest inValue = new ZolCo.ProductTests.BatchRunService.StartRegionRequest();
            inValue.clientName = clientName;
            inValue.regionName = regionName;
            inValue.userId = userId;
            ZolCo.ProductTests.BatchRunService.StartRegionResponse retVal = ((ZolCo.ProductTests.BatchRunService.IBatchService)(this)).StartRegion(inValue);
            outputMessage = retVal.outputMessage;
            return retVal.StartRegionResult;
        }
        
        public System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.StartRegionResponse> StartRegionAsync(ZolCo.ProductTests.BatchRunService.StartRegionRequest request) {
            return base.Channel.StartRegionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZolCo.ProductTests.BatchRunService.StopRegionResponse ZolCo.ProductTests.BatchRunService.IBatchService.StopRegion(ZolCo.ProductTests.BatchRunService.StopRegionRequest request) {
            return base.Channel.StopRegion(request);
        }
        
        public int StopRegion(string clientName, string regionName, string userId, out string outputMessage) {
            ZolCo.ProductTests.BatchRunService.StopRegionRequest inValue = new ZolCo.ProductTests.BatchRunService.StopRegionRequest();
            inValue.clientName = clientName;
            inValue.regionName = regionName;
            inValue.userId = userId;
            ZolCo.ProductTests.BatchRunService.StopRegionResponse retVal = ((ZolCo.ProductTests.BatchRunService.IBatchService)(this)).StopRegion(inValue);
            outputMessage = retVal.outputMessage;
            return retVal.StopRegionResult;
        }
        
        public System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.StopRegionResponse> StopRegionAsync(ZolCo.ProductTests.BatchRunService.StopRegionRequest request) {
            return base.Channel.StopRegionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZolCo.ProductTests.BatchRunService.KillJobResponse ZolCo.ProductTests.BatchRunService.IBatchService.KillJob(ZolCo.ProductTests.BatchRunService.KillJobRequest request) {
            return base.Channel.KillJob(request);
        }
        
        public int KillJob(string clientName, string regionName, int jobNumber, string userId, out string outputMessage) {
            ZolCo.ProductTests.BatchRunService.KillJobRequest inValue = new ZolCo.ProductTests.BatchRunService.KillJobRequest();
            inValue.clientName = clientName;
            inValue.regionName = regionName;
            inValue.jobNumber = jobNumber;
            inValue.userId = userId;
            ZolCo.ProductTests.BatchRunService.KillJobResponse retVal = ((ZolCo.ProductTests.BatchRunService.IBatchService)(this)).KillJob(inValue);
            outputMessage = retVal.outputMessage;
            return retVal.KillJobResult;
        }
        
        public System.Threading.Tasks.Task<ZolCo.ProductTests.BatchRunService.KillJobResponse> KillJobAsync(ZolCo.ProductTests.BatchRunService.KillJobRequest request) {
            return base.Channel.KillJobAsync(request);
        }
    }
}
